In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('student_performance.csv')

df.head()
# show top 5 rows

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [ ]:
df.tail()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [ ]:
print("shape of dataset:", df.shape)
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

# shape shows no of rows and column

shape of dataset: (30, 13)
Number of rows: 30
Number of columns: 13

In [ ]:
print(df.columns.tolist())

# prints column name

['student_id', 'name', 'age', 'gender', 'department', 'semester', 'math_score', 'science_score', 'english_score', 'programming_score', 'attendance_percentage', 'city', 'admission_year']

In [ ]:
df.columns.tolist()

['student_id',
 'name',
 'age',
 'gender',
 'department',
 'semester',
 'math_score',
 'science_score',
 'english_score',
 'programming_score',
 'attendance_percentage',
 'city',
 'admission_year']

In [26]:
df.dtypes

# shows datatype of columns

student_id                int64
name                     object
age                       int64
gender                   object
department               object
semester                  int64
math_score                int64
science_score             int64
english_score             int64
programming_score         int64
attendance_percentage     int64
city                     object
admission_year            int64
dtype: object

In [27]:
df.describe()

,student_id,age,semester,math_score,science_score,english_score,programming_score,attendance_percentage,admission_year
count,30.000000,30.000000,30.0,30.000000,30.000000,30.000000,30.000000,30.000000,30.0
mean,1015.500000,19.733333,2.0,76.066667,77.833333,74.166667,67.600000,84.500000,2023.0
std,8.803408,0.739680,0.0,11.467896,8.554423,10.003735,21.041175,9.379913,0.0
min,1001.000000,19.000000,2.0,56.000000,61.000000,55.000000,38.000000,65.000000,2023.0
25%,1008.250000,19.000000,2.0,67.250000,71.250000,67.250000,49.250000,77.250000,2023.0
50%,1015.500000,20.000000,2.0,75.500000,78.000000,75.000000,66.000000,86.500000,2023.0
75%,1022.750000,20.000000,2.0,85.750000,83.750000,81.750000,88.750000,91.750000,2023.0
max,1030.000000,21.000000,2.0,95.000000,93.000000,90.000000,97.000000,98.000000,2023.0

In [35]:
print("Missing values in each row and column :")
print(df.isnull())

print("Total Missing values in each column :")
print(df.isnull().sum())

print("Total missing values in whole dataset :")
print(df.isnull().sum().sum())

Missing values in each row and column :
    student_id   name    age  gender  department  semester  math_score  \
0        False  False  False   False       False     False       False
1        False  False  False   False       False     False       False
2        False  False  False   False       False     False       False
3        False  False  False   False       False     False       False
4        False  False  False   False       False     False       False
5        False  False  False   False       False     False       False
6        False  False  False   False       False     False       False
7        False  False  False   False       False     False       False
8        False  False  False   False       False     False       False
9        False  False  False   False       False     False       False
10       False  False  False   False       False     False       False
11       False  False  False   False       False     False       False
12       False  False  False   False       False     False       False
13       False  False  False   False       False     False       False
14       False  False  False   False       False     False       False
15       False  False  False   False       False     False       False
16       False  False  False   False       False     False       False
17       False  False  False   False       False     False       False
18       False  False  False   False       False     False       False
19       False  False  False   False       False     False       False
20       False  False  False   False       False     False       False
21       False  False  False   False       False     False       False
22       False  False  False   False       False     False       False
23       False  False  False   False       False     False       False
24       False  False  False   False       False     False       False
25       False  False  False   False       False     False       False
26       False  False  False   False       False     False       False
27       False  False  False   False       False     False       False
28       False  False  False   False       False     False       False
29       False  False  False   False       False     False       False

    science_score  english_score  programming_score  attendance_percentage  \
0           False          False              False                  False
1           False          False              False                  False
2           False          False              False                  False
3           False          False              False                  False
4           False          False              False                  False
5           False          False              False                  False
6           False          False              False                  False
7           False          False              False                  False
8           False          False              False                  False
9           False          False              False                  False
10          False          False              False                  False
11          False          False              False                  False
12          False          False              False                  False
13          False          False              False                  False
14          False          False              False                  False
15          False          False              False                  False
16          False          False              False                  False
17          False          False              False                  False
18          False          False              False                  False
19          False          False              False                  False
20          False          False              False                  False
21          False          False              False                  False
22          False          False              False                  False
23          False          False              False                  False
24          False          False              False                  False
25          False          False              False                  False
26          False          False              False                  False
27          False          False              False                  False
28          False          False              False                  False
29          False          False              False                  False

     city  admission_year
0   False           False
1   False           False
2   False           False
3   False           False
4   False           False
5   False           False
6   False           False
7   False           False
8   False           False
9   False           False
10  False           False
11  False           False
12  False           False
13  False           False
14  False           False
15  False           False
16  False           False
17  False           False
18  False           False
19  False           False
20  False           False
21  False           False
22  False           False
23  False           False
24  False           False
25  False           False
26  False           False
27  False           False
28  False           False
29  False           False
Total Missing values in each column :
student_id               0
name                     0
age                      0
gender                   0
department               0
semester                 0
math_score               0
science_score            0
english_score            0
programming_score        0
attendance_percentage    0
city                     0
admission_year           0
dtype: int64
Total missing values in whole dataset :
0

In [62]:
print("Students Names :")
print(df['name'])

print(df[['name', 'age', 'department']])

Students Names :
0       Aarav Sharma
1        Priya Patel
2        Rohit Verma
3        Sneha Reddy
4         Arjun Nair
5        Meera Joshi
6        Kiran Kumar
7        Divya Singh
8       Rahul Mishra
9         Ananya Das
10       Vikram Iyer
11       Pooja Gupta
12        Suresh Rao
13     Kavya Nambiar
14       Ajay Tiwari
15      Ritu Agarwal
16      Manoj Pandey
17    Swati Kulkarni
18    Deepak Chauhan
19      Nisha Kapoor
20     Harish Pillai
21       Tanvi Mehta
22      Sanjay Dubey
23     Preeti Saxena
24         Amit Bose
25        Rekha Nair
26     Gaurav Shukla
27     Sunita Pillai
28        Nitin Jain
29    Akanksha Yadav
Name: name, dtype: object
              name  age        department
0     Aarav Sharma   19  Computer Science
1      Priya Patel   20  Computer Science
2      Rohit Verma   19       Electronics
3      Sneha Reddy   20        Mechanical
4       Arjun Nair   19  Computer Science
5      Meera Joshi   20       Electronics
6      Kiran Kumar   21             Civil
7      Divya Singh   19  Computer Science
8     Rahul Mishra   20        Mechanical
9       Ananya Das   19  Computer Science
10     Vikram Iyer   20       Electronics
11     Pooja Gupta   19             Civil
12      Suresh Rao   21  Computer Science
13   Kavya Nambiar   20        Mechanical
14     Ajay Tiwari   19  Computer Science
15    Ritu Agarwal   20       Electronics
16    Manoj Pandey   21             Civil
17  Swati Kulkarni   19  Computer Science
18  Deepak Chauhan   20        Mechanical
19    Nisha Kapoor   19  Computer Science
20   Harish Pillai   20       Electronics
21     Tanvi Mehta   19  Computer Science
22    Sanjay Dubey   21             Civil
23   Preeti Saxena   20        Mechanical
24       Amit Bose   19  Computer Science
25      Rekha Nair   20       Electronics
26   Gaurav Shukla   21  Computer Science
27   Sunita Pillai   19             Civil
28      Nitin Jain   20        Mechanical
29  Akanksha Yadav   19  Computer Science

In [53]:
print("Departments in dataset:")
print(df['department'].unique())

print("Number of students in each department:")
print(df['department'].value_counts())

Departments in dataset:
['Computer Science' 'Electronics' 'Mechanical' 'Civil']
Number of students in each department:
department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

In [69]:
cs_students = df[df['department'] == 'Computer Science']

print("Number of Computer Science students: ", len(cs_students))

print(cs_students[['name', 'department', 'age', 'gender']])

Number of Computer Science students:  13
              name        department  age  gender
0     Aarav Sharma  Computer Science   19    Male
1      Priya Patel  Computer Science   20  Female
4       Arjun Nair  Computer Science   19    Male
7      Divya Singh  Computer Science   19  Female
9       Ananya Das  Computer Science   19  Female
12      Suresh Rao  Computer Science   21    Male
14     Ajay Tiwari  Computer Science   19    Male
17  Swati Kulkarni  Computer Science   19  Female
19    Nisha Kapoor  Computer Science   19  Female
21     Tanvi Mehta  Computer Science   19  Female
24       Amit Bose  Computer Science   19    Male
26   Gaurav Shukla  Computer Science   21    Male
29  Akanksha Yadav  Computer Science   19  Female

In [72]:
high_attendance = df[df['attendance_percentage'] > 90]

print("Total number of students with more than 90% attendance :", len(high_attendance))

high_attendance[['name', 'department']]

Total number of students with more than 90% attendance : 10

              name        department
0     Aarav Sharma  Computer Science
3      Sneha Reddy        Mechanical
7      Divya Singh  Computer Science
9       Ananya Das  Computer Science
13   Kavya Nambiar        Mechanical
15    Ritu Agarwal       Electronics
17  Swati Kulkarni  Computer Science
21     Tanvi Mehta  Computer Science
24       Amit Bose  Computer Science
29  Akanksha Yadav  Computer Science

In [1]:
df['total_score'] = df['math_score'] + df['science_score'] + df['english_score'] + df['programming_score']

top_student = df.loc[df['total_score'].idxmax()]

print(top_student)

NameError: name 'df' is not defined

In [ ]:
dept_avg = df.groupby('department')['total_score'].mean().round(2)
print("Average scores per department:")
print(dept_avg)

In [ ]:
df_sorted = df.sort_values('total_score', ascending=False)
print(df_sorted[['name','department','total_score']].head(10))